{org_abbrv, string, []}.
{directory, string, []}.
{host, string, []}.
{port, integer, []}.
{bind, string, []}.
{bind_pass, string, []}.
{tls, string_list, []}.
{autoregister, boolean, []}.
{attr_uid, string, []}.
{attr_mail, string, []}.
{attr_fname, string, []}.
{attr_lname, string, []}.
